name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: runner / hadolint (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: ./
        with:
          reporter: github-check
          level: info
          exclude: Dockerfile.dockerignore

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / hadolint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: ./
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          exclude: Dockerfile.dockerignore
